/* Exemplo sintetico - Hotfix Unifier
   Categoria esperada: 3 - IMPLEMENTACAO DE PROCEDURES/FUNCTIONS

   Corpo real da procedure, que depende da assinatura publicada no
   arquivo 02. Note que este arquivo NAO traz SET TERM: o Hotfix
   Unifier detecta os ';' internos ao bloco e envolve o comando
   automaticamente na saida unificada. */

CREATE OR ALTER PROCEDURE CALC_TOTAL_PEDIDO (
    IDPEDIDO BIGINT,
    APLICAR_DESCONTO SMALLINT)
RETURNS (
    VALOR_BRUTO NUMERIC(18,2),
    VALOR_DESCONTO NUMERIC(18,2),
    VALOR_IMPOSTO NUMERIC(18,2),
    VALOR_LIQUIDO NUMERIC(18,2))
AS
DECLARE VARIABLE PERCENTUAL NUMERIC(18,4);
DECLARE VARIABLE ALIQUOTA NUMERIC(18,4);
DECLARE VARIABLE UF VARCHAR(2);
BEGIN
  VALOR_BRUTO = 0;
  VALOR_DESCONTO = 0;

  SELECT COALESCE(SUM(I.QUANTIDADE * I.PRECO_UNITARIO), 0)
    FROM PEDIDO_ITENS I
   WHERE I.IDPEDIDO = :IDPEDIDO
    INTO :VALOR_BRUTO;

  IF (APLICAR_DESCONTO = 1) THEN
  BEGIN
    SELECT COALESCE(P.DESCONTO_NEGOCIADO, 0)
      FROM PEDIDOS P
     WHERE P.ID = :IDPEDIDO
      INTO :PERCENTUAL;

    VALOR_DESCONTO = VALOR_BRUTO * (PERCENTUAL / 100);
  END

  SELECT C.UF
    FROM PEDIDOS P
    JOIN CLIENTES C ON C.ID = P.IDCLIENTE
   WHERE P.ID = :IDPEDIDO
    INTO :UF;

  EXECUTE PROCEDURE APLICAR_REGRA_FISCAL(:IDPEDIDO, :UF)
    RETURNING_VALUES :ALIQUOTA;

  VALOR_IMPOSTO = (VALOR_BRUTO - VALOR_DESCONTO) * COALESCE(ALIQUOTA, 0);
  VALOR_LIQUIDO = VALOR_BRUTO - VALOR_DESCONTO + VALOR_IMPOSTO;
  SUSPEND;
END
