/* Exemplo sintetico - Hotfix Unifier
   Categoria esperada: 4 - TRIGGERS

   Registra na auditoria toda mudanca de status do pedido. */

CREATE OR ALTER TRIGGER TG_PEDIDOS_AUDITORIA FOR PEDIDOS
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
  IF (OLD.STATUS IS DISTINCT FROM NEW.STATUS) THEN
    INSERT INTO PEDIDOS_AUDITORIA (IDPEDIDO, STATUS_ANTERIOR, STATUS_NOVO, DATA_EVENTO)
    VALUES (NEW.ID, OLD.STATUS, NEW.STATUS, CURRENT_TIMESTAMP);
END
