/* Exemplo sintetico - Hotfix Unifier
   Categoria esperada: 5 - VIEWS */

CREATE OR ALTER VIEW VW_PEDIDOS_ABERTOS (
    ID, CLIENTE, DATA_EMISSAO, VALOR_LIQUIDO)
AS
SELECT P.ID,
       C.NOME,
       P.DATA_EMISSAO,
       T.VALOR_LIQUIDO
  FROM PEDIDOS P
  JOIN CLIENTES C ON C.ID = P.IDCLIENTE
  LEFT JOIN CALC_TOTAL_PEDIDO(P.ID, 1) T ON 1 = 1
 WHERE P.STATUS = 'ABERTO';
